<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="qasimsobeh-lt" name="com.qasim.test.CSVloginAndroid" tests="3" failures="0" timestamp="24 Jan 2018 20:04:06 GMT" time="142.975" errors="1">
  <testcase name="tearDown" time="1.002" classname="com.qasim.test.CSVloginAndroid">
    <error type="com.experitest.client.InternalException" message="Connectivity Exception, verify studio is open and the right port is been used">
      <![CDATA[com.experitest.client.InternalException: Connectivity Exception, verify studio is open and the right port is been usedat com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:192)at com.experitest.client.Client.execute(Client.java:247)at com.experitest.client.Client.releaseClient(Client.java:1792)at com.qasim.framework.BaseTest.tearDown(BaseTest.java:143)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.TestRunner.afterRun(TestRunner.java:725)at org.testng.TestRunner.run(TestRunner.java:509)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: org.apache.xmlrpc.XmlRpcException: Failed to read server's response: Connection refused: connectat org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:161)at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:115)at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)at com.experitest.client.JavaClientInternals.executeXmlRpcCommand(JavaClientInternals.java:285)at com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:189)... 27 moreCaused by: java.net.ConnectException: Connection refused: connectat java.net.DualStackPlainSocketImpl.connect0(Native Method)at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)at java.net.AbstractPlainSocketImpl.connect(Unknown Source)at java.net.PlainSocketImpl.connect(Unknown Source)at java.net.SocksSocketImpl.connect(Unknown Source)at java.net.Socket.connect(Unknown Source)at java.net.Socket.connect(Unknown Source)at sun.net.NetworkClient.doConnect(Unknown Source)at sun.net.www.http.HttpClient.openServer(Unknown Source)at sun.net.www.http.HttpClient.openServer(Unknown Source)at sun.net.www.http.HttpClient.<init>(Unknown Source)at sun.net.www.http.HttpClient.New(Unknown Source)at sun.net.www.http.HttpClient.New(Unknown Source)at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.writeRequest(XmlRpcSunHttpTransport.java:104)at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:151)... 35 more]]>
    </error>
  </testcase> <!-- tearDown -->
  <testcase name="Start" time="0.027" classname="com.qasim.test.CSVloginAndroid"/>
  <testcase name="Start" time="141.946" classname="com.qasim.test.CSVloginAndroid"/>
</testsuite> <!-- com.qasim.test.CSVloginAndroid -->
